# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: diego.tejadaarango@tno.nl
AuthorName: TNO
Indentation: 4
JuliaMinVersion: '1.6'
License: Apache-2.0
PackageName: TulipaProfileFitting
PackageOwner: TulipaEnergy
PackageUUID: 0aa31362-0b7e-4e8d-8385-676712fa7ef3
_commit: v0.7.0
_src_path: https://github.com/abelsiqueira/COPIERTemplate.jl
