name = "TulipaProfileFitting"
uuid = "0aa31362-0b7e-4e8d-8385-676712fa7ef3"
authors = ["Diego A. Tejada-Arango <diego.tejadaarango@tno.nl>", "Germán Morales-España <german.morales@tno.nl>", "Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.3.4"

[deps]
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"
Roots = "2"
Statistics = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
