name: "Addition Request"
description: Create a ticket to request a new addition (or feature)
title: "<title>"
labels: ["Type: addition"]
body:
    - type: textarea
      id: description
      attributes:
          label: "Description"
          description: Provide an explanation of the addition
          placeholder: Describe your addition request
      validations:
          required: true
    - type: textarea
      id: related_issues
      attributes:
          label: "Related Issues"
          description: Existing issues related to this addition
          placeholder: "#Issues IDs"
      validations:
          required: false
