name: "Improvement Request"
description: Create a ticket to request an improvement of something that already exists.
title: "<title>"
labels: ["Type: improvement"]
body:
    - type: textarea
      id: summary
      attributes:
          label: "What and Why"
          description: Explain the improvement
          placeholder: Describe your request, including why it's an improvement
      validations:
          required: true
    - type: textarea
      id: drawbacks
      attributes:
          label: "Possible Drawbacks"
          description: What are possible drawbacks of your improvement request?
          placeholder: Identify the drawbacks, while remaining neutral
      validations:
          required: false
    - type: textarea
      id: related_issues
      attributes:
          label: "Related Issues"
          description: Existing issues related to this improvement
          placeholder: "#Issues IDs"
      validations:
          required: false
